version: 2.0

parameters:
  build-workflow-only:
    type: boolean
    default: false

  test-workflow-only:
    type: boolean
    default: false

  broad-deployment-workflow-only:
    type: boolean
    default: false

  api:
    type: boolean
    default: false

orbs:
  heroku: circleci/heroku@1.2.2

jobs:
  deploy-to-heroku:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "deploy"
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "build"
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "test"

workflows:
    build:
      when:
        equal: [ << pipeline.parameters.api >> , << pipeline.parameters.build-workflow-only >> ]
      jobs:
        - build

    test:
      when:
        equal: [ << pipeline.parameters.api >>, << pipeline.parameters.test-workflow-only >> ]
      jobs:
        - test

    broad-deployment:
      when:
        equal: [ << pipeline.parameters.api >>, << pipeline.parameters.broad-deployment-workflow-only >> ]
      jobs:
        - deploy-to-heroku
